import { ArrowRight, BadgeCheck, Boxes, CreditCard, GitBranch, PackagePlus, Rocket } from "lucide-react";
import Link from "next/link";
import { notFound } from "next/navigation";

import { prisma } from "@/lib/prisma";
import { requireAdminPermission } from "@/modules/admin/admin-permission-guards";
import { addBundleComponentAction, addCatalogPriceAction, assignOfferingCapabilityAction, publishServicesProductAction, saveCatalogOfferingAction, saveServicesProductAction, saveTrialPolicyAction, setServicesProductStatusAction } from "../../actions";

const inputClass = "min-h-11 rounded-xl border border-white/10 bg-black/15 px-3 text-sm font-bold text-white outline-none placeholder:text-white/25 focus:border-amber-300/30";

export const dynamic = "force-dynamic";

export default async function AdminServicesProductPage({ params, searchParams }: { params: Promise<{ id: string }>; searchParams: Promise<{ error?: string; saved?: string; published?: string }> }) {
  await requireAdminPermission("services", "view");
  const { id } = await params;
  const query = await searchParams;
  const [product, workflows, allOfferings] = await Promise.all([
    prisma.productDefinition.findUnique({
      where: { id },
      include: {
        revisions: { orderBy: { revision: "desc" }, take: 8 },
        trialPolicies: { orderBy: { createdAt: "desc" } },
        offerings: {
          where: { deletedAt: null }, orderBy: { sortOrder: "asc" },
          include: {
            workflowTemplate: true,
            prices: { orderBy: { version: "desc" } },
            capabilities: { include: { capability: true } },
            bundleComponents: { include: { componentOffering: true } },
            trialPolicies: true,
          },
        },
      },
    }),
    prisma.workflowTemplate.findMany({ where: { isActive: true }, orderBy: [{ key: "asc" }, { version: "desc" }] }),
    prisma.catalogOffering.findMany({ where: { deletedAt: null }, select: { id: true, code: true, name: true, type: true }, orderBy: { name: "asc" } }),
  ]);
  if (!product) notFound();

  return (
    <div className="grid gap-6" dir="rtl">
      <Link href="/admin/services" className="inline-flex w-fit items-center gap-2 text-xs font-black text-white/45 no-underline hover:text-[#f3cf73]"><ArrowRight className="size-4" /> Product Registry</Link>
      <header className="rounded-[1.7rem] border border-white/10 bg-white/[0.03] p-6"><div className="flex flex-col gap-4 lg:flex-row lg:items-start lg:justify-between"><div><p className="text-xs font-black text-[#f3cf73]">{product.code} · adapter: {product.registryKey}</p><h1 className="mt-2 text-3xl font-black text-white">{product.name}</h1><p className="mt-2 max-w-2xl text-sm font-bold leading-6 text-white/43">{product.shortDescription}</p></div><div className="flex flex-wrap gap-2"><span className="rounded-full bg-white/[0.06] px-3 py-1.5 text-xs font-black text-white/60">{product.publicationStatus}</span><span className="rounded-full bg-blue-400/10 px-3 py-1.5 text-xs font-black text-blue-100">{product.releaseStage}</span><span className="rounded-full bg-amber-300/10 px-3 py-1.5 text-xs font-black text-[#f3cf73]">rev {product.publishedRevision ?? "—"}</span></div></div></header>
      {query.error ? <div role="alert" className="rounded-2xl border border-red-300/20 bg-red-500/10 p-4 text-sm font-bold text-red-100">{query.error}</div> : null}{query.saved ? <div className="rounded-2xl border border-emerald-300/18 bg-emerald-400/8 p-4 text-sm font-bold text-emerald-100">تم حفظ {query.saved}.</div> : null}{query.published ? <div className="rounded-2xl border border-emerald-300/18 bg-emerald-400/8 p-4 text-sm font-bold text-emerald-100">نُشرت نسخة Catalog جديدة بنجاح.</div> : null}

      <section className="grid gap-4 lg:grid-cols-[1fr_20rem]"><form action={saveServicesProductAction} className="grid gap-3 rounded-[1.5rem] border border-white/8 bg-white/[0.025] p-5 md:grid-cols-2"><input type="hidden" name="id" value={product.id} /><h2 className="font-black text-white md:col-span-2">تعريف المنتج</h2><input required name="name" defaultValue={product.name} className={inputClass} /><input required name="code" defaultValue={product.code} dir="ltr" className={inputClass} /><input required name="registryKey" defaultValue={product.registryKey} dir="ltr" className={inputClass} /><input required name="category" defaultValue={product.category} dir="ltr" className={inputClass} /><input required name="shortDescription" defaultValue={product.shortDescription} className={`${inputClass} md:col-span-2`} /><textarea name="description" defaultValue={product.description ?? ""} rows={3} className={`${inputClass} py-3 md:col-span-2`} /><input name="tags" defaultValue={Array.isArray(product.tags) ? product.tags.join(", ") : ""} dir="ltr" className={inputClass} /><select name="releaseStage" defaultValue={product.releaseStage} className={inputClass}><option value="ANNOUNCED">Coming Soon</option><option value="PRIVATE_PREVIEW">Private Preview</option><option value="BETA">Beta</option><option value="GA">GA</option><option value="DEPRECATED">Deprecated</option></select><input name="accessTier" defaultValue={product.accessTier} dir="ltr" className={inputClass} /><input name="sortOrder" type="number" defaultValue={product.sortOrder} className={inputClass} /><textarea name="eligibilityPolicy" defaultValue={product.eligibilityPolicy ? JSON.stringify(product.eligibilityPolicy, null, 2) : ""} dir="ltr" rows={4} placeholder="Eligibility policy JSON" className={`${inputClass} py-3 font-mono text-xs md:col-span-2`} /><label className="flex items-center gap-2 text-sm font-bold text-white/55"><input type="checkbox" name="isFeatured" defaultChecked={product.isFeatured} /> Featured</label><button className="min-h-11 rounded-xl bg-white/10 px-4 text-sm font-black text-white hover:bg-white/15" type="submit">حفظ التعريف</button></form>
        <aside className="grid content-start gap-3 rounded-[1.5rem] border border-amber-300/12 bg-amber-300/[0.035] p-5"><h2 className="font-black text-white">النشر والتحكم</h2><form action={publishServicesProductAction} className="grid gap-2"><input type="hidden" name="productId" value={product.id} /><input name="changeNote" placeholder="ملاحظة الإصدار" className={inputClass} /><button className="min-h-11 rounded-xl bg-[#f3cf73] px-4 text-sm font-black text-[#17130a]"><Rocket className="ml-2 inline size-4" /> Preview ثم Publish</button></form><div className="grid grid-cols-2 gap-2">{["PAUSED", "RETIRED", "DRAFT"].map((status) => <form key={status} action={setServicesProductStatusAction}><input type="hidden" name="productId" value={product.id} /><input type="hidden" name="status" value={status} /><button className="min-h-10 w-full rounded-xl border border-white/10 bg-white/[0.035] px-2 text-xs font-black text-white/55">{status}</button></form>)}</div><div className="border-t border-white/8 pt-3"><p className="text-xs font-black text-white/40">آخر الإصدارات</p>{product.revisions.map((revision) => <div key={revision.id} className="mt-2 flex items-center justify-between text-xs font-bold text-white/45"><span>Revision {revision.revision}</span><span>{revision.status}</span></div>)}</div></aside></section>

      <section className="grid gap-4"><div><p className="text-xs font-black text-[#f3cf73]">Offerings</p><h2 className="mt-1 text-xl font-black text-white">العروض والأسعار والقدرات</h2></div>{product.offerings.map((offering) => <article key={offering.id} className="rounded-[1.6rem] border border-white/9 bg-white/[0.03] p-5"><div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div><div className="flex flex-wrap gap-2"><span className="rounded-full bg-white/[0.055] px-2 py-1 text-[0.62rem] font-black text-white/50">{offering.type}</span><span className="rounded-full bg-blue-400/8 px-2 py-1 text-[0.62rem] font-black text-blue-100">{offering.salesMode}</span><span className="rounded-full bg-emerald-400/8 px-2 py-1 text-[0.62rem] font-black text-emerald-100">{offering.fulfillmentMode}</span></div><h3 className="mt-3 text-lg font-black text-white">{offering.name}</h3><p className="mt-1 text-xs font-bold text-white/35">{offering.code} · {offering.workflowTemplate?.key ?? "بدون Workflow"}</p></div><span className="text-xs font-black text-white/40">{offering.publicationStatus}</span></div>
          <div className="mt-5 grid gap-4 xl:grid-cols-3"><div className="rounded-xl bg-black/10 p-4"><p className="flex items-center gap-2 text-xs font-black text-[#f3cf73]"><CreditCard className="size-4" /> Pricing versions</p>{offering.prices.map((price) => <div key={price.id} className="mt-2 flex items-center justify-between text-xs font-bold text-white/48"><span>{(price.amount / 100).toLocaleString("ar-EG")} {price.currency} / {price.billingInterval}</span><span>v{price.version}{price.isActive ? " · active" : ""}</span></div>)}<form action={addCatalogPriceAction} className="mt-4 grid grid-cols-2 gap-2"><input type="hidden" name="productId" value={product.id} /><input type="hidden" name="offeringId" value={offering.id} /><input required type="number" step="0.01" name="amount" placeholder="السعر" className={inputClass} /><input name="currency" defaultValue="EGP" className={inputClass} /><select name="billingInterval" className={inputClass}><option value="ONE_TIME">مرة واحدة</option><option value="MONTHLY">شهري</option><option value="YEARLY">سنوي</option></select><input name="marketCode" defaultValue="EG" className={inputClass} /><button className="col-span-2 min-h-10 rounded-lg bg-white/9 text-xs font-black text-white">إضافة Price version</button></form></div>
            <div className="rounded-xl bg-black/10 p-4"><p className="flex items-center gap-2 text-xs font-black text-emerald-200"><BadgeCheck className="size-4" /> Capabilities</p>{offering.capabilities.map((item) => <div key={item.id} className="mt-2 text-xs font-bold text-white/48">{item.capability.key} = {JSON.stringify(item.value)} <span className="text-white/25">({item.capability.aggregationPolicy})</span></div>)}<form action={assignOfferingCapabilityAction} className="mt-4 grid gap-2"><input type="hidden" name="productId" value={product.id} /><input type="hidden" name="offeringId" value={offering.id} /><input required name="capabilityKey" placeholder="capability.key" dir="ltr" className={inputClass} /><input name="capabilityName" placeholder="الاسم" className={inputClass} /><div className="grid grid-cols-2 gap-2"><select name="aggregationPolicy" className={inputClass}><option>REPLACE</option><option>SUM</option><option>MAX</option><option>UNION</option><option>BOOLEAN_OR</option></select><input name="capabilityValue" defaultValue="true" dir="ltr" className={inputClass} /></div><button className="min-h-10 rounded-lg bg-white/9 text-xs font-black text-white">ربط القدرة</button></form></div>
            <div className="rounded-xl bg-black/10 p-4"><p className="flex items-center gap-2 text-xs font-black text-blue-200"><Boxes className="size-4" /> Bundles & Trials</p>{offering.bundleComponents.map((item) => <p key={item.id} className="mt-2 text-xs font-bold text-white/48">{item.componentOffering.name} × {item.quantity}</p>)}{offering.trialPolicies.map((trial) => <p key={trial.id} className="mt-2 text-xs font-bold text-violet-200">{trial.name} · {trial.durationDays ?? "usage"}</p>)}{offering.type === "BUNDLE" ? <form action={addBundleComponentAction} className="mt-4 grid gap-2"><input type="hidden" name="productId" value={product.id} /><input type="hidden" name="bundleOfferingId" value={offering.id} /><select required name="componentOfferingId" className={inputClass}><option value="">مكوّن الحزمة</option>{allOfferings.filter((item) => item.id !== offering.id).map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select><input name="quantity" type="number" min="1" defaultValue="1" className={inputClass} /><label className="text-xs font-bold text-white/50"><input type="checkbox" name="required" defaultChecked /> إلزامي</label><button className="min-h-10 rounded-lg bg-white/9 text-xs font-black text-white">إضافة للحزمة</button></form> : null}<form action={saveTrialPolicyAction} className="mt-4 grid grid-cols-2 gap-2"><input type="hidden" name="productId" value={product.id} /><input type="hidden" name="offeringId" value={offering.id} /><input name="name" defaultValue="تجربة مجانية" className={`${inputClass} col-span-2`} /><input name="durationDays" type="number" placeholder="أيام" className={inputClass} /><input name="usageLimit" type="number" placeholder="حد الاستخدام" className={inputClass} /><input name="graceDays" type="number" defaultValue="0" className={inputClass} /><label className="text-xs font-bold text-white/50"><input type="checkbox" name="oncePerTenant" defaultChecked /> مرة واحدة</label><button className="col-span-2 min-h-10 rounded-lg bg-violet-400/10 text-xs font-black text-violet-100">إضافة Trial Policy</button></form></div></div></article>)}

        <details className="rounded-[1.5rem] border border-dashed border-white/12 bg-white/[0.02] p-5"><summary className="flex cursor-pointer list-none items-center gap-2 font-black text-white"><PackagePlus className="size-4 text-[#f3cf73]" /> إضافة Offering</summary><form action={saveCatalogOfferingAction} className="mt-5 grid gap-3 md:grid-cols-2"><input type="hidden" name="productId" value={product.id} /><input required name="name" placeholder="اسم العرض" className={inputClass} /><input required name="code" placeholder="offering-code" dir="ltr" className={inputClass} /><input required name="shortDescription" placeholder="وصف مختصر" className={`${inputClass} md:col-span-2`} /><textarea name="description" placeholder="الوصف" rows={2} className={`${inputClass} py-3 md:col-span-2`} /><select name="type" className={inputClass}>{["PLAN", "ADD_ON", "ONE_TIME_SERVICE", "MANAGED_SERVICE", "BUNDLE", "CUSTOM_QUOTE"].map((item) => <option key={item}>{item}</option>)}</select><select name="salesMode" className={inputClass}>{["SELF_SERVE", "REQUEST", "QUOTE_ONLY", "CONTACT_ONLY"].map((item) => <option key={item}>{item}</option>)}</select><select name="fulfillmentMode" className={inputClass}>{["AUTOMATIC", "MANUAL", "HYBRID", "EXTERNAL"].map((item) => <option key={item}>{item}</option>)}</select><select name="activationMode" className={inputClass}>{["INSTANT", "AFTER_PAYMENT", "AFTER_APPROVAL", "SCHEDULED"].map((item) => <option key={item}>{item}</option>)}</select><select name="workflowTemplateId" className={inputClass}><option value="">Workflow</option>{workflows.map((workflow) => <option key={workflow.id} value={workflow.id}>{workflow.key} v{workflow.version}</option>)}</select><select name="releaseStage" className={inputClass}>{["ANNOUNCED", "PRIVATE_PREVIEW", "BETA", "GA"].map((item) => <option key={item}>{item}</option>)}</select><textarea name="requirements" placeholder="Requirements JSON" dir="ltr" rows={3} className={`${inputClass} py-3 font-mono text-xs`} /><textarea name="eligibilityPolicy" placeholder="Eligibility JSON" dir="ltr" rows={3} className={`${inputClass} py-3 font-mono text-xs`} /><button className="min-h-11 rounded-xl bg-[#f3cf73] px-4 text-sm font-black text-[#17130a] md:col-span-2"><GitBranch className="ml-2 inline size-4" /> إنشاء العرض</button></form></details>
      </section>
    </div>
  );
}
