import { dirname, join } from "node:path";
import { readFile } from "node:fs/promises";
import { createFrameIdRestorePipeline } from "./frameid-backup-pipeline";
import { createRestoreService } from "./backup-restore-service";
import { createVerificationService } from "./backup-verification-service";
import { getGitHubBackupBranch } from "./backup-job-service";
import type { BackupManifest } from "./backup-manifest";
import { validateCustomerDataCounts, type CustomerDataCounts } from "./customer-data-inventory";

type Client = { backupJob: { updateMany(i: unknown): Promise<unknown>; upsert(i: unknown): Promise<unknown> }; restoreJob: { count(i: unknown): Promise<number>; create(i: unknown): Promise<{ id: string }>; updateMany(i: unknown): Promise<unknown>; upsert(i: unknown): Promise<unknown> }; auditLog: { create(i: unknown): Promise<unknown> } };
export function createOfficialRestorePipeline(input: { prisma: Client; databaseUrl: string; backupRoot?: string; uploadsDir?: string; githubToken?: string; githubRepository?: string }) { const root = input.backupRoot ?? process.env.BACKUP_DIR ?? join(process.cwd(), "backups"); const service = createRestoreService(); const verifier = createVerificationService(); let expectedCounts: CustomerDataCounts | null = null; let restoredManifest: BackupManifest | null = null; let restoredBackupDir: string | null = null; return createFrameIdRestorePipeline({
  async createJob(command) { if (await input.prisma.restoreJob.count({ where: { status: { in: ["PENDING", "RUNNING"] } } })) throw new Error("توجد استعادة قيد التنفيذ"); return input.prisma.restoreJob.create({ data: { backupJobId: command.backupId, status: "RUNNING", triggeredById: command.actorId }, select: { id: true } }); },
  async resolve(c) { const artifact = await service.ensureBackupAvailable({ backupId: c.backupId, backupRoot: root, type: c.type, githubToken: input.githubToken, githubRepository: input.githubRepository, githubBranch: getGitHubBackupBranch(c.type) }); restoredBackupDir = artifact.backupDir; return artifact; },
  async verify(c) { const result = await verifier.verifyBackup(c.backupId, dirname(c.backupDir)); if (result.valid) { const manifest = JSON.parse(await readFile(join(c.backupDir, "manifest.json"), "utf8")) as BackupManifest; restoredManifest = manifest; expectedCounts = manifest.customerDataCounts ?? { usersCount: manifest.usersCount, tenantsCount: manifest.tenantsCount, sitesCount: manifest.sitesCount, mediaFilesCount: manifest.mediaFilesCount }; } return { valid: result.valid, errors: result.errors }; },
  async apply(c) { const result = await service.applyVerifiedRestore({ backupDir: c.backupDir, databaseUrl: input.databaseUrl, uploadsDir: input.uploadsDir, type: c.type }); if (!result.success) throw new Error(result.errors.join("; ")); },
  async verifyRestored() { const isUploadsOnly = restoredManifest?.backupType === "UPLOADS"; if (isUploadsOnly) { const uCheck = restoredManifest?.uploadsInventory ? await service.validateRestoredUploads(input.uploadsDir ?? join(process.cwd(), "public", "uploads"), restoredManifest.uploadsInventory) : { valid: true, errors: [] }; return uCheck; } const result = await service.validatePostRestore(input.databaseUrl); if (!result.passed || !expectedCounts || !restoredManifest) return { valid: false, errors: [...result.errors, ...(!expectedCounts || !restoredManifest ? ["تعذر قراءة Manifest للتحقق بعد الاستعادة"] : [])] }; const countsCheck = validateCustomerDataCounts(expectedCounts, result.counts); const uploadsCheck = (restoredManifest.backupType === "FULL" || restoredManifest.backupType === "UPLOADS") && restoredManifest.uploadsInventory ? await service.validateRestoredUploads(input.uploadsDir ?? join(process.cwd(), "public", "uploads"), restoredManifest.uploadsInventory) : { valid: true, errors: [] }; return { valid: countsCheck.valid && uploadsCheck.valid, errors: [...countsCheck.errors, ...uploadsCheck.errors] }; },
  async audit(e) { await input.prisma.auditLog.create({ data: { actorId: e.actorId, action: e.action, entityType: "RestoreJob", entityId: e.jobId, metadata: { ...e.metadata, backupId: e.backupId } } }); },
  async complete(e) { const recoveredAt = new Date(); await input.prisma.backupJob.updateMany({ where: { status: { in: ["PENDING", "RUNNING"] } }, data: { status: "FAILED", completedAt: recoveredAt, errorMessage: "أُغلقت المهمة القديمة بعد عودة الطوارئ" } }); await input.prisma.restoreJob.updateMany({ where: { status: { in: ["PENDING", "RUNNING"] } }, data: { status: "FAILED", completedAt: recoveredAt, errorMessage: "أُغلقت المهمة القديمة بعد عودة الطوارئ" } }); if (restoredManifest && restoredBackupDir) { const branch = getGitHubBackupBranch(e.type); const repository = input.githubRepository?.trim().replace(/^https?:\/\/github\.com\//, "").replace(/\.git$/, ""); await input.prisma.backupJob.upsert({ where: { id: restoredManifest.backupJobId }, update: { type: e.type, status: "COMPLETED", filePath: restoredBackupDir, sizeBytes: restoredManifest.totalSizeBytes, checksumSha256: restoredManifest.checksum, completedAt: new Date(restoredManifest.createdAt), errorMessage: null, metadata: { trigger: "MIGRATION", githubBranch: branch, githubPath: repository ? `https://github.com/${repository}/tree/${branch}/backups/${e.backupId}` : null, externalStorage: "github", localVerified: true, githubUploaded: true, remoteVerified: true, retentionApplied: true, auditLogged: true } }, create: { id: restoredManifest.backupJobId, type: e.type, status: "COMPLETED", filePath: restoredBackupDir, sizeBytes: restoredManifest.totalSizeBytes, checksumSha256: restoredManifest.checksum, createdAt: new Date(restoredManifest.createdAt), completedAt: new Date(restoredManifest.createdAt), metadata: { trigger: "MIGRATION", githubBranch: branch, githubPath: repository ? `https://github.com/${repository}/tree/${branch}/backups/${e.backupId}` : null, externalStorage: "github", localVerified: true, githubUploaded: true, remoteVerified: true, retentionApplied: true, auditLogged: true } } }); } await input.prisma.restoreJob.upsert({ where: { id: e.jobId }, update: { backupJobId: e.backupId, status: "COMPLETED", completedAt: recoveredAt, targetDatabase: `${e.source}:${e.type}` }, create: { id: e.jobId, backupJobId: e.backupId, status: "COMPLETED", triggeredById: e.actorId, completedAt: recoveredAt, targetDatabase: `${e.source}:${e.type}` } }); },
  fail: (e) => input.prisma.restoreJob.upsert({ where: { id: e.jobId }, update: { backupJobId: e.backupId, status: "FAILED", completedAt: new Date(), errorMessage: e.reason }, create: { id: e.jobId, backupJobId: e.backupId, status: "FAILED", triggeredById: e.actorId, completedAt: new Date(), errorMessage: e.reason, targetDatabase: `FAILED:${e.type}` } }).then(() => undefined),
}); }
